#% text_encoding = iso8859_1
##
## Name:          ghc_swd_netzstoerung_framework.msg
##
## Description:   Message file for message handler ghc_swd_netzstoerung_framework
##
## Author:        Uli Nädelin
## Date:          20. Nov 2017
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
:title			Content Analyst Auswertungen in Lovion
:refresh		Dialog aktualisieren
:only_connected		Nur Layer mit CA Auswertung
:vm_module		Thema
:vm_view_configuration	CA Auswertung
:filter_view_configuration Nur ausgewählte CA Auswertung
:connect		   Verknüpfe Layer mit CA Auswertung
:disconnect		   Entferne Verknüpfung mit CA Auswertung
