#% text_encoding = iso8859_1
##
## Name:          ghc_swd_netz_list_plugin.msg
##
## Description:   Message file for message handler ghc_swd_netz_list_plugin
##
## Author:        Uli Nädelin
## Date:          19. Nov 2017
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
:column_heading		Lovion Projekte, Kategorien & Layer
:missing_view_configuration    Keine CA Auswertung mit ID #1 gefunden

