#% text_encoding = iso8859_1
##
## Name:          ghc_swd_netzstoerung_plugin.msg
##
## Description:   Message file for message handler ghc_swd_netzstoerung_plugin
##
## Author:        Uli Nädelin
## Date:          24. Oct 2017
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
:activate_ca_lovion		Content Analyst Auswertungen in Lovion
:operation_requires_write_access		Vorgang benötigt Schreibzugriff auf Datenbank #1.

