#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          bplan_data_model.msg
##
## Description:   Message file for message handler bplan_data_model
##
## Author:        Uli Nädelin
## Date:          31. Jul 2008
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:gc_forstkataster	Forst Standorteinheiten
:gc_fk_regzonale_einheit      Regzonale Einheit
:gc_fk_wuchsbezirk	      Wuchsbezirk
:gc_fk_wuchsgebiet	      Wuchsgebiet
:gc_fk_standortseinheit	      Standorteinheit
:create_flaeche_from_standortseinheit	Fläche nach Standorteinheiten ausrichten
:create_flaeche_from_standortseinheit_short	Fläche ausrichten
:create_flaeche_from_standortseinheit_description	Fläche nach Standorteinheiten ausrichten
:create_flaeche_from_regzonale_einheit	Fläche nach Regzonaler Einheiten ausrichten
:create_flaeche_from_regzonale_einheit_short	Fläche ausrichten
:create_flaeche_from_regzonale_einheit_description	Fläche nach Regzonaler Einheiten ausrichten
:create_flaeche_from_wuchsbezirk	Fläche nach Wuchsbezirken ausrichten
:create_flaeche_from_wuchsbezirk_short	Fläche ausrichten
:create_flaeche_from_wuchsbezirk_description	Fläche nach Wuchsbezirken ausrichten
:area_created					Fläche neu ausgerichtet.
