#% text_encoding = iso8859_1
##
## Name:          ghc_wo_component_application.msg
##
## Description:   Message file for message handler ghc_wo_component_application
##
## Author:        Uli Nädelin
## Date:          01. Jan 2019
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##

:tsm			Time Series Management
:wo_component_toolbar	WO Components
