:ok			OK	
:abbruch		Abbruch
:apply			Übernehmen
:quit			Beenden
:set_target_coll			Ziel Kollektion auswählen
:auto_generate_target_mapping		Zuordnung automatisch erzeugen
:add			Hinzufügen
:remove			Entfernen
:remove_all		Alle Entfernen
:set_source		Wähle Quelle
:set_target		Wähle Ziel
:set_source_value		Wähle Ausgangswert
:set_destination_value		Wähle Zielwert
:edit			Bearbeiten
:actions		Aktionen
:help		Hilfe
:target_collection		Ziel Kollektion
:target_attributes		Ziel Attribute
:source_attributes		Quell Attribute
:mappings		Zuordnungen
:source_attribute_value		Attributwert der Quelle
:busy		Aktiv!
:mapping_editor_for		GIT HydroS Consult Data Communicator - Zuordnungseditor für #1
:source_name		Quellname
:source_value		Quellwert
:target_name		Zielname
:target_value		Zielwert
:please_enter		Eingabefenster
:show_internal_classname?		Internen Klassennamen anzeigen
:active_file 	 	Aktuell #1
:curent_file 		Aktuelle Datei: #1
:add_mapping 	 	Hinzufügen
:generate_source_mapping 	 	Hinzufügen -> Quelle generieren
:edit_mapping 	 	Bearbeiten
:reverse_mapping 	 	Umkehren
:default_import 	 	Als Standardimport speichern
:default_export 	  Als Standardexport speichern
:save_mappings	 	Mappings speichern
:load_mappings		Mappings laden
:import		 	Importieren	
:export			Exportieren
:import_list		Liste importieren
:interrupt		Unterbrechen
:select_file		Datei/Dateiliste auswählen
:select_directory		Verzeichnis auswählen
:set_limit		Anzahl Datensätze begrenzen
:transform	 	Transformieren
:geo_correction		Geometriefehlerbehebung
:method_mapping	 	Hook-Mapping
:remove_mapping		Entfernen
:level_up		höhere Ebene  
:Level_down		niedrigere Ebene 
:add_field_mapping 		Feldmapping hinzufügen
:shorten_fieldname		Feldnamen automatisch kürzen
:parent_class_names_name_label		Übergeordnete Objektklasse:
:map_to				Zuordnung zu : 
:copy_to_db			In Datenbank schreiben
:no_view			Kein Datenbestand ausgewählt
:no_class_selected		Keine Datenbankobjektklasse ausgewählt
:level				Ebene
:external_fieldname_already_exists	 	Externer Feldname existiert bereits im Mapping, nicht hinzugefügt!
:child_liste			Untergeordnete Objektklassen
:fields				Felder
:object_classes			Objektklassen
:navigation			Navigation
:ghc_mapping_definator		HydroS Consult Mapping Definator
:gis_views			GIS Datenbestand
:transferlist_in_db		Transfers in Datenbank
:new_transfer			Neuer Transfername:
:start_git_coll_browser			Starte Objektabfrage
:edit_mappings				Zuordnungen Bearbeiten
:transferlist_in_db			Transfers in Datenbank
:new_transfer				Neuer Transfer
:transfer_name_exists_sure?		Transfername existiert bereits. Trotzdem verwenden ?
:yes					Ja
:no					Nein
:make_new_transfer			Neuen Transfer erzeugen
:no_transfer_selected			Kein Transfer ausgewählt
:delete_selected_transfer		Transfer löschen
:really_delete_transfer?		Gewählten Transfer '#1' wirklich löschen, Sind sie Sicher ?
:git_collection_browser_title		GIT HydroS Consult Objekt Abfrage #1
:fortschrittsanzeige			Fortschritt	
:filename			  Dateiname
:interrupt				Unterbrechen
:reset					Zurücksetzen
:quit				  Beenden
:export_to_shape			Exportiere Shape
:file_exists_overwrite?			Datei existiert bereits, überschreiben?
:determining_bounds			Bestimme geographische Grenzen
:no_action				Keine Aktivität
:start_shapeexport			Beginne Shape Export
:checking_fieldtypes			Prüfe Feldtypen
:counting_fields_and_records		Zähle Datensätze
:opening_shapefile_for_writing		Öffne Shapefile (schreibend)
:exporting				Exportiere
:closing_shape				Schließe Shapefile
:cleanup				Aufräumen... 
:nr_of_nr				Aktuell: #1 von #2
:completed				Beendet		
:parent_mapping_unset_moveup!		Elternzuordnung wurde nicht ausgewählt, Wechsel in höhere Ebene!
:max_number_of_geometry_fields_already_selected!		Maximale Anzahl der Geometriefelder ist schon zugeordnet (#1) 
:edit_or_delete				Bearbeiten oder Löschen?
:edit					Bearbeiten
:delete					Löschen
:really?				Sind Sie sich wirklich sicher?
:fieldldmap				Feld > #1 < zugeordnet auf externen Feldnamen > #2 <
:class					(#1) Klasse > #2 
:coordinate_system			Koordinatensystem
:filename_missing			Dateiname fehlt!
:mappings_of_transfer_missing	  Transfer hat keine Mappings!
:please_select_transfer			Bitte Transfer auswählen!
:no_csys_selected			Kein Koordinatensystem ausgewählt!
:path_not_found				Pfad nicht gefunden!
:mapping_not_found			Mapping nicht gefunden!
:file_does_not_exist			Shape-Datei (#1) existiert nicht!
:opening_shapefile			Öffne Shape-Datei
:reading_shapefile			Lese Shape-Datei
:read_from_shape			Importiere Shape-Datei


:db_char			 	Zeichenkette
:db_date				Datum
:db_logical				Ja/Nein (Logisch)
:db_decimal				Numerisch
:db_unsupported			 	nicht unterstützt

:dataset				Datensätze
:istat_alternative_label		Alternative:
:istat_file_label			Dateiname:
:istat_mapping_label			Feldzuordnung:
:istat_target_collection_label		Ziel (Tabelle):
:istat_number_records_label		Anzahl Datensätze:
:istat_info_label			Weitere Informationen:
:istat_import_or_reimport?_label		Import/Reimport?
:ready_for_import?			Ok für Import?
.estat_info_label			 
:estat_file_label			Dateiname:
:estat_mapping_label			Feldzuordnung:
:estat_source_collection_label		Quelle (Tabelle):
:estat_number_records_label		Anzahl Datensätze:
:estat_key_field_export_label		Schlüsselfelder:
:estat_complete_for_reimport_label		Komplett für Reimport?
:estat_csystem_label			Koordinatensystem
:istat_csystem_label			Koordinatensystem
:ready_for_export?			Ok für Export? 

:childs 				Kinder
:child_map_error			 	Fehler bei untergeordneter Zuordnung
:main_map_error				Fehler bei Hauptzuordnung
:nicht_alle_kinder_gefunden		Notwendige Kindzuordnungens fehlen!
:pflichtfelder_nicht_gemappt		Pflichtfelder nicht gemappt
:kinder_nicht_gesund			Untergeorndete Zuordnungen haben Fehler!
:custom_transformation 			Benutzerdefinierte Transformation:
:on_off					An/Aus?
:ctrans_magnification_label		Skalierung
:ctrans_translation_label		Translation X | Y
:ctrans_translation_x_label		Translation X
:ctrans_translation_y_label		Translation Y
:ctrans_rotation_label			Rotation (Grad)
:ctrans_side_label			Anwenden auf  
:ctrans_reihenfolge_label		Reihenfolge   
:rotation				Rotation
:translation				Translation
:magnification				Skalierung
:external_csys				Externes Koordinatensystem
:internal_csys				GIS Koordinatensystem
:around_coord				um Koordinate X | Y
:save_on_transfer_label		  Speichern in Transfer?
:no_suitable_results_avaliable		Keine passenden Datensätze gefunden!
:information_on_selected_transfer		Informationen zum gewählten Transfer:
:user_translation_available			Benutzer Transformation vorhanden
:no_user_translation_available			Keine Benutzer Transformation vorhanden
:coordinate_system_named			Koord. System: #1	
:mapping_information				Zuordnungsinformationen: 
:more_than_x_found				... mehr als #1 gefunden... 
:in						in
:none						keine
:results_in_classbrowser			Ergebnisse der Objektabfrage
:class_browser_open				Objektabfrage geöffnet
:cb_matching_mappings				Passende Ergebnisse
:class_browser_not_open				Objektabfrage ist nicht geöffnet!
:check_class_browser				Prüfe Objektabfrage
:no_filename_selected				Kein Dateiname ausgewählt!
:import_und_export_info				Import oder Export?
:export_custom_options				Besondere Exportoptionen:
:import_custom_options				Besondere Importoptionen:
:export_settings				Exporteinstellungen:
:polygon_reduction?				Polygonzahl reduzieren?
:really_reset?					Wirklich zurücksetzen?
:yes						Ja
:no					  Nein
:no_transfer_selected				Kein Transfer ausgewählt
:found_fields					Gemappte Dateifelder: #1
:other_mapping_label				Andere Mappings
:error_detected_going_to_checkpoint		Fehler ! Gehe zurück zu Markierungspunkt : #1
:existing_record_found_updating		Bestehender Datensatz gefunden. Aktualisiere...
:generating_new_record				Erzeuge neuen Datensatz...
:write_field_values				Schreibe Feldwerte
:check_catalogue_values				Prüfe Katalogwerte
:check_mandatory_fields				Prüfe Pflichtfelder
:inserting_record				Füge Datensatz ein...
:updating_record				Aktualisiere Datensatz...
:updating_geometry				Aktualisiere Geometrie...
:done						Fertig
:write_records_to_db				Schreibe Datensätze in Datenbanktabelle: #1
:wrote_record					Datensatz #1 nach #2 geschrieben. 
:record_processed				Datensatz #1 bearbeitet. 
:done_successfully				Erfolgreich beendet
:error_occurred					Ein Fehler ist aufgetreten. 
:noaction					Keine Aktivität
:insert_childs					Füge relationale Datensätze ein
:action						Aktivität
:info						Information
:writing_to_database				Schreibe in Datenbank...
:save_stats					Statusinformationen speichern
:looking_for_unset_geometries			Suche ungesetzte Geometrien...
:error_accessing_catalogue_fields		Fehler beim Zugriff auf Katalogfelder
:error_converting_field_value			Fehler beim Konvertieren von Wert (#1) für Feld #2
:importing_without_geometry			Import ohne Geometrien! 
:opening_dbfile					Öffne DBASE Datei
:reading_dbfile					Lese DBASE Datei
:no_coordinate_system_selected			Kein Koordinatensystem ausgewählt.
:shp						ESRI Shape#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s	
:dbf						DBASE#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s
:mdb						MS Access#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s
:txt						ASCII-TXT#s#s#s#s#s#s#s#s#s#s#s#s#s#s#s
:git_msaccess_accessor_missing			GIT MS-Access Zugriffsschicht fehlt! Installation prüfen (Modul GIT Office Core)
:records_read					#1 Datensätze gelesen
:importing_access_data				Importiere Daten aus MS Access 
:importing_finished			  Import beendet. #1 Datensätze gelesen. 
:no_access_tables_found				Keine Access Tabellen gefunden!
:opening_access_table				Öffne Access Tabelle "#1"
:error_writing_record				Fehler beim Schreiben von Datensatz #1, evtl. schon vorhanden!
:clear_mdb_table				Access Tabelle leeren?
:added_record_number_to_mdb			Datensatz #1 zu Access Datenbank hinzugefügt.
:start_writing_mdb_records			Beginne mit dem Schreiben von Access Datensätzen.
:clearing_mdb_table				Leere MS Access Tabelle "#1"
:no_suitable_results_available		  Kein passendes Ergebnis gefunden, bitte Objektabfrage prüfen.
:add_catalogue_values?				Katalogwerte ergänzen?	
:hint_add_catalogue_values 			Wenn Werte in Felder importiert werden, auf denen Katalogzuordnungen definiert sind, kann hier versucht werden die Kataloge um die entsprechenden Einträge zu erweitern (Bei einigen Katalogen ist das automatische Erzeugen von Objekten nicht möglich.) ACHTUNG: Mit besonderer Vorsicht anwenden! Es wird empfohlen, die Kataloge vor dem Import zu überprüfen um eine evtl. unübersichtliche Füllung der Kataloge zu vermeiden!
:error_inserting_or_updating_record		Fehler beim Aktualisieren/Einfügen des Datensatzes. 
:error_details					Details: #1
:record_insertion_not_possible			Datensatz konnte nicht eingefügt werden. Mapping und Einstellungen prüfen.
:warning_mandatory_field_unset			Warnung! Pflichtfeld leer! Datensatz #1, Feld #2, Typ #3 
:dcc_requires_write_access_to_dsview		"DCC benötigt Schreibzugriff auf Datenbestand #1! Versionskontrolle öffnen?"
:error_internal_field_for_mapping_not_found		Internes GIS Feld für Mappingfeld #1 nicht gefunden! Prüfen!
:mappingnames_too_long				Mappingfeldnamen (#1) zu lang (max. 10 Ziffern)
:cut_name					Ändere in: #1
:cancel_export					Export abbrechen
:add_changed_field?				"geändert" Feld hinzufügen?
:hint_add_changed_field				Fügt Boolsches Feld für den Import hinzu
:start_dbfexport				Beginne DBASE Export...

:only_import_changed?				Nur geänderte Importieren?
:hint_only_import_changed			Bei Auswahl dieser Option werden nur Datensätze importiert, die im Feld "gitchanged" den Wert True/Wahr/T/t/J/j haben .

:warning_gitchanged_not_found_really_import_all_data? 	Warnung Feld "gitchanged" nicht gefunden für die selektive Rücknahme nicht gefunden! Sollen wirklich alle Datensätze importiert werden?

:no_records_to_import				Keine Datensätze zum Importieren Vorhanden!
:filtering_out_datasets_without_gitchanged_flag 	Filtere Datenätze ohne "gitchanged" Schalter aus... 
:filtering_out_done_x_of_y_left			Filtern beendet. #1 Datensätze werden importiert (Gesamt: #2) 
:gitchanged_status_label			Feld 'gitchanged' gefunden?

:no_formats_check_installation!			FEHLER: Keine vom DCC unterstützten Formate gefunden! Installation prüfen und ggf. wiederholen!

:konnte_mapping_info_nicht_ermitteln        Konnte Mapping-Informationen nicht ermitteln!

:mapped_table_not_found_in_database		Zugeordnete Tabelle '#1' wurde nicht in den Datenbeständen gefunden!

:please_wait					Bitte warten...
:checking_class_browser_results			Prüfe Abfrageergebnis der Objektabfrage...
:checking_clipboard_contents			Prüfe Inhalt der Smallworld Zwischenablage...
:git_dcc_working				Das GIT Data Communication Center arbeitet für Sie...
:close_progress_window				Fortschrittsfenster nach Beenden schließen?
:bad_catalogue_mapping				Katalogzuordnung fehlt! Bitte Katalog #1 prüfen!

:record_not_processed_successfully		Datensatz wurde NICHT ordnungsgemäß eingefügt/aktualisiert!
:some_records_had_errors		  Bei einigen Datensätzen sind Fehler aufgetreten!
:start_transfer_browser				Wähle Transfer (Abfrage)
:git_transferabfrage				GIT DCC - Transferabfrage
:selected_transfer				Ausgewählter Transfer:
:no_records					Keine Datensätze gefunden!
:no_records_with_that_geometry_found		Keine Datensätze mit der gewählten Geometrie gefunden!
:process_aborted					Vorgang abgebrochen!
:not_all_selected_records_have_this_geometry!		Nicht alle ausgewählten Datensätze haben eine Geometrie! 
:kein_passendes_abfrageergebnis_gefunden		Kein passendes Abfrageergebnis gefunden, evtl. stimmen die (internen und externen) Tabellennamen in Abfrage/Zwischenablage und Mapping nicht überein!
:show_only_visible_fields			Nur sichtbare Felder anzeigen
:exportvorgang_fortgesetzt			Exportvorgang wird fortgesetzt
:exportvorgang_unterbrochen			Exportvorgang wurde unterbrochen
:exportvorgang_beendet			 	Exportvorgang ist abgeschlossen
:importvorgang_fortgesetzt			Importvorgang wird fortgesetzt
:importvorgang_unterbrochen			Importvorgang wurde unterbrochen
:importvorgang_beendet			 	Importvorgang ist abgeschlossen
:validate_data					Importdaten werden validiert
:exportvorgang_gestartet			Exportvorgang wurde gestartet
:importvorgang_gestartet			Importvorgang wurde gestartet
:activate_prozess_manager			Prozessmanager zeigen
:starte_import					Import-Prozess initialisieren
:starte_export					Export-Prozess initialisieren
:verknuepfe_obj					Verknüpfung mit Objekt
:enumerator				  Zuordnung für Enumerator-Feld
:string_als_zahl				Zeichenkette als Zahl 
:int_rundung					Rundung auf ganze Zahlen
:wertebereich					Wertebereich
:unbekannt					Standard-Problemtyp
:string_zu_lang					Zeichenkette zu lang
:convert_date_time				Problemwert für Datums-Feld
:catalogue_value				Zuordnung für Katalog-Feld
:pflichtfeld					Wert für Pflichtfeld
:wirklich_beenden				Wollen Sie den Data-Communicator wirklich beenden?
:recs_found					#1 Datensätze in Ablage '#2' gefunden
:check_scrapbook				Ablage-Daten neu laden
:transfer_ok_for_import			 	Transfer für Import geeignet?
:total_transfer_info				Transfers in Datenbank:
:select_git_transfer_from_editor		Setze Transfer von Editor
:activate_git_transfer_editor			Aktiviere Transfer Editor
:start_writing_to_db				Schreibe Import-Daten in Datenbank
:more_than_one_transfer_with_that_name_found 	Mehr als ein Transfer mit dem Namen '#1' gefunden! Öffne Explorer!
:transfer					Transfer:
:search!					Suchen!
:transfer_not_found_create?			Transfer nicht gefunden, erzeugen?
:ghc_transfers_browse_collection		GHC Transfersuche [DCC] nach '#1'
:please_enter_transfer_name			Bitte Transfernamen eingeben!
:field_name_does_not_exist			Ungültiger Feldname
:field_name_does_not_exist_detail		'#1' besitzt kein Feld mit internem Namen '#2' 
:updated_records				Aktualisierte Datensätze
:unchanged_records				Unveränderte Datensätze
:no_record_with_key				Kein Datensatz mit diesem Schlüssel
:record_exist_no_change				Datensätze existieren, keine Veränderung
:dcc_insertion					DCC: Datensatz einfügen
:dcc_update					DCC: Datensatz aktualisieren
:record_number					Datensatz Nr. #1
:key_fields					Schlüsselfelder:
:no_changes_done_on_record			Keine Änderungen am Datensatz vorgenommen
:import_info_not_imported_because_of_existing_data		Importinformation, die aufgrund bestehender Daten im Objekt nicht importiert wurden:
:current_value_in_field_kept 			Aktueller Wert im Feld #1 : '#2' (beibehalten) / Importinformation '#3' verworfen
:current_value_in_field_overridden		Aktueller Wert im Feld #1 : '#2' / Überschriebener Wert: '#3'
:information_added				Informationen, die ergänzt wurden:
:actual_value_in_field				Aktueller Wert im Feld #1: '#2'
:geometry_replaced_by_import_geometry		Geometrie #1 wurde durch Import-Geometrie ersetzt.
:area_size_unchanged				Flächengröße unverändert (#1)
:area_size_changed_from_to			Flächengröße von #1 (Ursprungsfläche) auf eine Fläche von #2 geändert.
:line_length_unchanged				Linienlänge unverändert (#1)
:line_length_changed_from_to			Linienlänge von #1 (Ursprungslinie) auf eine Länge von #2 geändert.
:point_geometry_unchanged			Punkt-Geometrie unverändert
:point_geometry_changed_by_distance		Punktgeometrie um #1 von Ursprungspunkt verschoben
:existing_geometry_unchanged			Bestehende Geometrie '#1' unverändert von Import
:new_geometry_created				Neue Geometrie '#1' angelegt
:information_overridden_by_import		Informationen, die durch Import überschrieben wurden:
:new_records					Neue Datensätze
:join_record_not_unique				Verknüpfter Datensatz nicht eindeutig
:join_record_not_unique_detail			Die verknüpfte Tabelle #1 besitzt im Feld '#2' #3 Einträge mit dem Wert '#4'.
:more_than_one_geom_field 			Es existiert mehr als ein Geometriefeld.
:fieldmap		 			Feld '#1' ist zugeordnet zu externem Feld '#2'
:duplicate_keys					Doppelte Schlüsselfelder 
:collection_not_found				Tabelle '#1' nicht gefunden
:table_info					Ebene #1: Tabelle #2 (#3 Felder)
:field_mapping					- #1: #2
  
