#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_dcc_engine.msg
##
## Description: Message file for message handler ghc_dcc_engine
##
## Author:      Uli Nädelin
## Date:        26. Jul 2006
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------
:export_data_validation	:de_de	Validierung Export-Daten
:export_dcc_data	:de_de	DCC Daten-Export
:export_dcc_data_short	:de_de	DCC Exp
:export_dcc_data_description	:de_de	DCC Daten-Export
:data_export		:de_de	DCC Exportiere Daten
:import_data_validation	:de_de	DCC Prüfe Import-Daten
:import_dcc_data	:de_de	DCC Daten-Import
:import_dcc_data_short	:de_de	DCC Imp
:import_dcc_data_description	:de_de	DCC Daten-Import
:read_shp_import_data	:de_de	Lese Shp-Importdatei
:read_dbf_import_data	:de_de	Lese Dbf-Importdatei
:no_bounds_detected_no_data?	:de_de	Konnte keine Geometriegrenzen ermitteln - es sind keine Geometriedaten vorhanden!
:cs_info_coordinate_system_information	:de_de	**** Information zum Koordinatensystem ****
:cs_info_projection		:de_de	Projektion: #1
:cs_info_unit			:de_de	Einheit: #1 (#2)
:cs_info_proj_type		:de_de	Projektionstyp #1 mit folgenden Parametern:
:cs_info_transformation		:de_de	Transformation besitzt folgende Eigenschaften:
:cs_info_datum_and_ellipsoid	:de_de	Datum: #1  (Ellipsoid: #2)
:unknown			:de_de	Unbekannt
:cs_info_no_proj_param		:de_de	-- Keine Projektionsparameter vorhanden
:field_to_long			:de_de	Externer Feldname für SHP / DBF zu lang
:problem_fieldname		:de_de	Der externe Feldname '#1' ist zu lang für DBF-Dateien (max. 10 Zeichen).#n#nÄndere Namen auf den Wert: 
:field_already_exist		:de_de	Externer Feldname existiert bereits
:new_fieldname_already_exist	:de_de	Der eingegebene Feldname '#1' existiert bereits.#n#nBitte wählen Sie einen anderen Namen für das Feld '#2':
:detail_filename_exists_overwrite?	:de_de	Warnung: Datei '#1' existiert bereits.
:yes_override_file		:de_de	Überschreibe Datei
:no_cancel_export		:de_de	Export abbrechen
:geometry_not_found		:de_de	Geometriefeld #1 auf OKL #2 nicht gefunden.
:no_geometry_in_mapping_defined	:de_de	Kein gültiges Geometriefeld im Mapping definiert.