#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_dcc_import_engine.msg
##
## Description: Message file for message handler ghc_dcc_import_engine
##
## Author:      Uli Nädelin
## Date:        26. Jul 2006
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------
:start_data_validation	:de_de	Überprüfe Daten-Validität