#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_dcc_export_task_def.msg
##
## Description: Message file for message handler ghc_dcc_export_task_def
##
## Author:      Uli Nädelin
## Date:        26. Jul 2006
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------
