#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          magikfan_source_code_cleanup_plugin.msg
##
## Description:   Message file for message handler magikfan_source_code_cleanup_plugin
##
## Author:        GIT HydroS Consult GmbH
## Date:          26. Apr 2011
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:new_file_separator	------
:message_converted_direction	Convertion from #1 to #2
:add_message			New messages added
:delete_message			Deleted messages
