#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_shape_file.msg
##
## Description: Message file for message handler ghc_shape_file
##
## Author:      Uli Nädelin
## Date:        25. Jan 2007
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------

:no_file_access		:de_de	Kein Schreibzugriff auf Datei
:no_file_access_detail	:de_de	Kein Schreibzugriff auf die Datei '#1'