#% text_encoding = iso8859_1
##
## Name:          ghc_rt_plugin.msg
##
## Description:   Message file for message handler ghc_rt_plugin
##
## Author:        SW Admin
## Date:          15. Aug 2011
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##

:terminate_dialog		Abbruch
:terminate_dialog_tt		Abbruch
:start_transfer			GW-Gleichenplan anlegen
:start_transfer_tt		Legt einen neuen GW-Gleichenplan mit den Daten der gewählten Interpolation an.
:gw_level_name_tt		Name des neuen GW-Gleichenplans
:gw_level_name_label		GW-Gleichenplan Name:	
:no_contour_map_selected	Bitte wählen Sie einen Interpolationsplan in der oberen Liste aus.
:name_for_groundwater_situation_missing	Bitte geben Sie einen Namen für den neu zu erzeugenden GW-Gleichenplan ein.
:name_for_groundwater_situation_already_exists	Es existiert bereits ein GW-Gleichenplan mit dem Namen '#1'.#nBitte wählen Sie einen anderen Namen.
:gw_situation_created_do_quit	GW-Gleichenplan wurde erfolgreich angelegt.#nWollen Sie den Dialog 'Übertrage GW-Plan' schließen?