#% text_encoding = iso8859_1
##
## Name:          ghc_rt_framework.msg
##
## Description:   Message file for message handler ghc_rt_framework
##
## Author:        SW Admin
## Date:          15. Aug 2011
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
:title		Übertrage GW-Plan