#% text_encoding = iso8859_1
##
## Name:          ghc_record_transfer_plugin.msg
##
## Description:   Message file for message handler ghc_record_transfer_plugin
##
## Author:        SW Admin
## Date:          25. Aug 2011
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##

:activate_ggs_cm_tr_dialog	Übertrage GW-Plan...
:activate_ggs_cm_tr_dialog_tt	Dialog zum übertragen von GW-Plänen