#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          bp_rwo_record_editor_plugin.msg
##
## Description:   Message file for message handler bp_rwo_record_editor_plugin
##
## Author:        Jan Kiefer
## Date:          12. Aug 2008
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:create_area_via_sa	:de_de	Füllflächen-Menu