#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          bplan_data_model.msg
##
## Description:   Message file for message handler bplan_data_model
##
## Author:        Uli Nädelin
## Date:          05. Aug 2008
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:not_relevant_in_level		:de_de	Nicht relevant für aktuelle Ebene
:no_world_fnp_neu		:de_de	Andere Welt als 'FNP-Neu'
:skipped_world_fnp_neu		:de_de	Übersprungen, da Welt 'FNP-Neu'
:overlapment_exist		:de_de	Übersprungen, da Überschneidung mit FNP-Neu-Fläche
:no_area_geom			:de_de	Keine Flächengeometrie
:no_bauflaeche_exist		:de_de	Baufenster keiner Baufläche zugeordnet
:no_geometry_exist		:de_de	Keine Flächengeometrie vorhanden
:bauflaeche_with_more_than_one_baufenster	:de_de	Baufläche mit mehr als einem Baufenster
:bauflaeche_geom_created	:de_de	Fläche des Baufensters erfolgreich auf Baufläche übertragen
:bauflaeche_contains_geom	:de_de	Baufläche besitzt bereits eine Fläche
:new_baufenster_created		:de_de	Neues Baufenster angelegt
:baufenster_geom_updated	:de_de	Baufensterfläche aktualisiert
:flaeche_baufenster_same_size	:de_de	Fläche des Baufensters gleich groß wie Baufläche