#% text_encoding = iso8859_1
#----------------------------------------------------------------------
#
# Name:        condition.msg
#
# Description: Meldungsdatei für it_geo_tools
#
# Author:      Jens Lüttke
#
# Date:        Nov. 2004
#
# Copyright (C) 2004 by ITS GmbH, Kaufbeuren
#
#----------------------------------------------------------------------

:it_geo_tools_no_reference_ellipsoid		:de_de
Erstellung nicht möglich, da kein Referenzellipsoid spezifiziert wurde oder ermittelt werden konnte.
