#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_dcc_application_actions_plugin.msg
##
## Description: Message file for message handler ghc_dcc_application_actions_plugin
##
## Author:      Jan Kiefer
## Date:        30. Mar 2006
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------
:activate_dcc_dialog	:de_de	DCC öffnen
:activate_dcc_dialog_tt	:de_de	DCC - Schnittstelle