#% text_encoding = iso8859_1
:title				Mapquest Geocoding
:status				Status :
:help_bh			Help for #1

:street				Street :
:gc_street_bh			Street Name

:city				City :
:gc_city_bh			City Name

:state				State :
:gc_state_bh			State Name

:postalcode			Postal Code :
:gc_postalcode_bh		Postal Code

:country			Country :
:gc_country_bh			Country Name

:location			Location :
:resultcode			Result Code :
:find				Find
:gc_find_bh			Find geocoding

:clear				Clear
:gc_clear_bh			Clear results

:goto				Goto
:gc_goto_bh			Goto results bounds on Map

:reverse			Reverse
:gc_reverse_bh			Reverse geocoding

:get_address_for_geocode	Address
:gc_get_address_bh		Get address for geocode from the Map Trail

:demo				Demo
:geocode			Geocoding
:geocode_results_bh		Geocoding results

:get_address_for_route		Address

:word_bh			Export to Word
:excel_bh			Export to Excel
:scrapbook_bh			Copy to Scrapbook

:set_origin			Set Origin
:set_destination		Set Destination
:goto				Goto
:highlight			Highlight
:blink				Blink
:origin				Origin
:destination			Destination

:route_result_bh		Routing result
:route				Routing
:narrative			Narrative
:distance			Distance
:time				Time

:rt_o_street_bh			Street name for origin
:rt_o_city_bh			City name for origin
:rt_o_state_bh			State name for origin
:rt_o_postalcode_bh		Postal code for origin
:rt_o_country_bh		Country name for origin
:rt_d_street_bh			Street name for destination
:rt_d_city_bh			City name for destination
:rt_d_state_bh			State name for destination
:rt_d_postalcode_bh		Postal code for destination
:rt_d_country_bh		Country name for destination

:rt_find_bh			Find routing
:rt_clear_bh			Clear routing results
:rt_goto_bh			Goto routing results on Map
:rt_get_results_bh		Get address for route from the Map Trail

:sc_criteria_bh			Search criteria List
:sc_max_matches_bh		Maximum number of serch results
:sc_dblayer_name_bh		DB Layer name for searching POI
:sc_extra_criteria_bh		Extra criteria name
:sc_server_bh			Server type name for searching POI

:sc_find_bh			Find POI
:sc_clear_bh			Clear searching results
:sc_goto_bh			Goto searching results on Map
:get_poi_detail			Get Detail

:name				Name
:key				Key
:source_layer_name		Source Layer Name
:dt				DT
:gefid				GEF ID
:distance			Distance
:category			Category

:search				Search
:parameter			Parameters
:search_criteria		Criteria type :
:circle				Circle
:rectangle			Rectangle
:search_max_matches		Max Matches
:search_dblayer_name		DB Layer Name
:search_extra_criteria		Extra criteria
:search_server			Server Type
:map				Map
:geocode			Geocode
:route				Route
:spatial			Spatail
:category			Category

:configuration			Configuration
:connection_spec		Connection Spec

:set_config			Set Config
:set_config_bh			Set the Configuration for Mapquest Server

:view_config			View config
:view_config_bh			View configuration for Mapquest Server

:restart_engine			Restart Engine
:restart_engine_bh		Restart engine with connection to Mapquest server

:map_display_option		Map display options
:auto_coverage_switching	Auto coverage switching
:swithcing_name			Name :
:mo_coverage_switching_name_bh	Coverage swithing Name
:style				Style :
:coverage_switching_style_bh	Map display style
:default			Default
:bw				Blank and White
:european			European
:style5				Style 5
:unset				Unset
:content_type			Content Type :
:content_type_bh		Map generation image type
:apply_bh			Apply changes
:geocode_option			Geocode Options
:specified_coverage		Specified Coverage
:reverse_geocode		Reverse Geocode
:map_coverage			Map Coverage :
:map_coverage_bh		Map coverage Name
:geocode_coverage		Geocode Coverage :
:geocode_coverage_bh		Geocode Coverage Name
:route_options			Route Options
:max_route_points		Max Points :
:map_route_points_bh		Number of maximum route results
:route_type			Route Type :
:fastest			Fastest
:shortest			Shortest
:fedestrian			Avoid fedestrian
:optimized			Optimized
:select_dataset_only		Selected Dataset Only
:route_type_bh			Type for routing
:narrative_type			Narrative Type :
:narrative_type_bh		Narritive type
:narrative_distance_unit	Narrative Distance Unit :
:ro_display_color		Display Color :
:ro_display_color_bh		Route Display Color
:red				Red
:green				Green
:blue				Blue
:yellow				Yellow
:purple				Purple
:ro_display_style		Display Style :
:ro_display_style_bh		Route Display Style
:solid				Solid
:dash				Dash
:dashdot			Dash Dot
:dashdotdot			Dash Dot Dot
:ro_display_width		Display Width :
:ro_display_width_bh		Route Display Style Width
:mile				Mile
:kilometer			Kilometer
:narrative_distance_unit_bh	Unit of narrative distance
:avoid_road_category		Road category to avoid :
:which_accecpt			Which Accept
:limited_access			Limited Access
:limited_access_bh		Limited Access
:toll_road			Toll Road
:toll_road_bh			Toll Road
:ferry				Ferry
:ferry_bh			Ferry
:seasonal			Seasonal
:seasonal_bh			Seasonal
:unpaved_road			Unpaved Road
:unpaved_road_bh		Unpaved Road