:ghc_no_values_found						:de_de	Für das Datum wurden keine Grundwasserhöhen gefunden!
:ghc_calculate_gw_impact_kanal_untersuchung			:de_de	Ermittelt die Lage im Grundwasser für alle AW Kanaluntersuchungen
:ghc_calculate_gw_impact_schacht_untersuchung			:de_de	Ermittelt die Lage im Grundwasser für alle AW Schachtuntersuchungen
:ghc_calculate_groundwater_situation				:de_de	Ermittlung der Grundwasserbeeinflussung für
