#% text_encoding = iso8859_1
##
## Name:          ghc_cf_data_model.msg
##
## Description:   Message file for message handler ghc_cf_data_model
##
## Author:        Uli Nädelin
## Date:          13. Jan 2014
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##

:friedhof			Friedhof
