#% text_encoding = iso8859_1
##
## Name:          ghc_cf_explorer_visualisation_plugin.msg
##
## Description:   Message file for message handler ghc_cf_explorer_visualisation_plugin
##
## Author:        GIT HydroS Consult GmbH
## Date:          21. Jan 2014
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##

