#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_filter_options_panel.msg
##
## Description: Message file for message handler ghc_filter_options_panel
##
## Author:      Uli Nädelin
## Date:        17. May 2007
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------
:ghc_smart_area_filter_options	:de_de	Füllflächen Content Analyst
