#% text_encoding = iso8859_1
##
## Name:          ghc_zuordnungs_menu.msg
##
## Description:   Message file for message handler ghc_zuordnungs_menu
##
## Author:        Uli Nädelin
## Date:          02. Jan 2013
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##

:wert				Problemwert:
:datentyp			Datentyp:
:zieldatenfeld			Zieldatenfeld
:objektklasse			Objektklasse:
:feldname			Feldname:
:laenge				#sLänge:#s
:eindeutige_elemente_nur_2000_wert	Eindeutige Feldwerte (2000 von #1):
:eindeutige_elemente			Eindeutige Feldwerte (Wert-Umwandlung):
:rundung				Zahlen für Feld immer (Methode):
:kaufmaennisch_runden			Kaufmännisch runden
:aufrunden				Aufrunden
:abrunden				Abrunden
:methodenname_unset			Kein Methodenname definiert
:no_method_defined			Keine Methode definiert
:field_method_found			Feldspezifische Methode erkannt.
:methode_result				Methode liefert den Wert #1 zurück.
:methode_versteht_nachricht_nicht	Objektklasse #1 versteht die Nachricht #2 nicht.
:methode_result				Aufruf der Methode #1 führt zu einem Fehler
:vordere_ziffern_kuerzen		Vordere Ziffern abschneiden (Methode):
:hintere_ziffern_kuerzen		Hintere Ziffern abschneiden (Methode):
:cut_time				Zeitkomponente verwerfen (Methode):
:umwandlung_in				Umwandlung durch Wert:
:wertebereich_von_bis			Wertebereich von #1 bis #2
:direkte_werte_umwandlung		Direkte Werte-Umwandlung:
:entspricht_feld			Zuordnung über Feld (Methode):
:eindeutige_elemente			Eindeutige Feldwerte (Wert-Umwandlung)
:oeffne_objekt_editor			Öffne Objekt-Editor
:ersetze_teile				Ersetze Teile des Strings (Methode):
:ersetze				Ersetze:
:durch					Durch
:umwandlung_durch_methode		Umwandlung durch Methode:
:test					Test
:ja					Ja
:nein					Nein
:bestehende_methode_ueberschreiben	Soll die bestehende Methode #1 durch die Neue ersetzt werden?
:als_unset_wert				Nichtgesetzter Wert (unset)
:zuordnen				Zuordnen
:abbrechen				Abbrechen
