#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_dcc_dialog.msg
##
## Description: Message file for message handler ghc_dcc_dialog
##
## Author:      Jan Kiefer
## Date:        31. Mar 2006
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------

:ghc_dcc_dialog		Data Communication Center - Smallworld 4.3

:hint_polygon_reduction 	 Wenn Flächengeometrien aus mehreren Polygonen bestehen, können diese hier (soweit geometrisch möglich) in eine Flächengeometrie aus einem Polygon konvertiert werden.

:import_export				Möchten Sie Daten exportieren oder importieren?

:mapped_table_not_found_in_database 	Zugeordnete Tabelle '#1' wurde nicht in den Datenbeständen gefunden!
:check_clipboard			Prüfe Zwischenablage...
:mapped_table_was_not_found_in_database		Die im Mapping zugeordnete Tabelle wurde nicht in den Datenbeständen gefunden!
:dateiformat					Dateiformat wählen
:clipboard					Zwischenablage
:scrapbook					Ablage
:export_source					Wählen Sie die Datenquelle für den Export
:start_ghc_mapping_definator			Bearbeite Feldzuordnung
:ablage_recs_found				#1 Datensätze in Ablage '#2' gefunden
:recs_found					#1 Datensätze in Zwischenablage gefunden
:please_choose_transfer				Bitte Transfer auswählen!
:do_not_close					Methode #1 wird ausgeführt. Menu kann nicht geschlossen werden
:methode_nicht_abgeschlossen			Methode #1 ist noch nicht abgeschlossen. Trotzdem beenden?
:convert_dos?					Korrigiere Umlaute?
:file_does_not_exist				Datei (#1) existiert nicht!
:no_name_given!					Kein Transfername angegeben!
:dcc_requires_write_access_to_dsview_to_execude_action		Aktion kann nicht ausgeführt werden, da Schreibzugriff auf Datenbestand #1 benötigt wird! Versionskontrolle öffnen?
:pathname_does_not_exist			Verzeichnis #1 existiert nicht. Bitte legen Sie das Verzeichnis an oder geben Sie ein anderes Verzeichnis ein.
:transfer_cs_different_from_selected_cs		Im Transfer gespeichertes Koordinatensystem (#1) weicht vom aktuellen Koordinatensystem (#2) ab. #nWelches Koordinatensystem soll für den Import gewählt werden?
:choose_tranfer_cs				#1 (Tranfer-Koord.-System)
:choose_existing_cs				#1 (Aktuelles Koord.-System)
:no_file_access					Kein Zugriff auf Datei #1-
:csv						Kommagetrennte Werte (CSV)
:checking_ghc_content_filter			Prüfe Content Analyst
:checking_all_records				Übernehme alle Datensätze
:inside_view					Im Plan
:inside_trail					In Hilfslinie
:check_inside_view				Im aktuellen Plan dargestellte Datensätze
:check_inside_trail				Im Hilfslinienzug liegende Datensätze
:recs_found_in_inside_view			#1 Datensätze im Plan ermittelt
:no_suitable_results_available_for_inside_view		 Es konnten keine gültigen Datensätze über den Plan ermittelt werden.
:result_name1					#1 (1 Datensatz)
:result_name					#1 (#2 Datensätze)
:checking_inside_view_contents			Prüfe im Plan gezeichnete Datensätze...
:no_matching_inside_view_records		Keine für den Export gültigen Datensätze im Plan gefunden.
:checking_inside_trail_contents			Prüfe Datensätze innnerhalb des Hilflinienzugs.
:trail_not_closed				Der Hilfslinienzug muss in sich geschlossen sein.
:no_suitable_results_available_for_trail		Kein passendes Ergebnis für Hilfslinienzug.
:transfer_without_geometry_field		Gewählter Export-Transfer besitzt kein Geometriefeld.
:no_matching_inside_trail_records		Keine für den Export gültigen Datensätze innerhalb des Hilflinienzugs gefunden.
:recs_found_in_inside_trail			#1 Datensätze innerhalb Hilfslinienzug
:dcc_requires_write_access_to_dsview		DCC benötigt Schreibzugriff auf Datenbestand #1! Versionskontrolle öffnen?
:yes						Ja
:no						Nein
:total_transfer_info				Transfers in Datenbank:
:selected_transfer				Ausgewählter Transfer:
:transfer_ok_for_import				Transfer für Import geeignet?
:information_on_selected_transfer		Informationen zum gewählten Transfer:
:coordinate_system				Koordinatensystem
:custom_transformation				Benutzerdefinierte Transformation:
:on_off						An/Aus ?
:ctrans_magnification_label			
:ctrans_translation_label			Translation (X|Y)
:ctrans_rotation_label
:around_coord					um Koordinate (X|Y)
:ctrans_reihenfolge_label			Reihenfolge?
:ctrans_side_label				Anwenden auf?
:external_csys					Extern
:internal_csys					Intern
:save_on_transfer_label				Speichern in Transfer?
:results_in_classbrowser			Ergebnisse der Objektabfrage
:exportsource					Export aus:
:all_records					Alle Datensätze
:ghc_content_filter				Content Analyst
:check_all_records				Übernehme alle Datensätze
:check_content_filter				Hole mit Content Analyst gefilterte Datensätze
:check_scrapbook				Ablage-Daten neu laden
:activate_prozess_manager			Aktiviere Prozessmanager
:save_export_transfer_information		Speichere Exporteinstellungen
:einlese_option					Einleseoption
:other_mapping_label				Anderes Mapping
:target_database_view_label			Zieldatenbestand
:ausfuehrliche_auswertungsinformationen		Ausführliche Auswertungsinformationen? (ungeeignet für große Daten-Importe)
:try_quit_process_manager			Prozessmanager beenden
:save_import_transfer_information		Speichere Importeinstellungen
:name_of_saved_transfer_information		Name der gespeicherten Einstellung:
:abbruch					Abbruch
:dataset					Datensätze
:found_fields					Gefundene Felder: #1
:git_dcc_working				Das GIT Data Communication Center arbeitet für Sie...
:please_wait					Bitte warten...
:n_rec_of_child					(#1 DS von #2 #3)
:n_records					(#1 Datensätze)
:no_valid_view_for_class_name_found		Kein gültiger Datenbestand für Klasse #1 gefunden
:no_records_in_collection			Keine Datensätze in Tabelle
:no_records_permitted_in_content_filter		Keine Datensätze im Content Analyst zulässig
:transfer_coordinate_system_named		KS (Transfer):#t#1
:choosen_coordinate_system_named		KS (verwendet):#t#1
:in						in
:konnte_mapping_info_nicht_ermitteln		Konnte Mapping-Informationen nicht ermitteln!
:really_reset?					Möchten Sie die Einstellungen zurücksetzen?
:wirklich_beenden				Wollen Sie den Data-Communicator wirklich beenden?
:read_header					Lese Dateiheader
:header_information				Feldinformationen#s
:geometry					Geometrie
:no_geometry_field_name				Kein Geometriefeldname angegeben
:checkpoint_removed				Checkpoint entfernt
:shp_file_does_not_exist			Shape-Datei (#1) existiert nicht!
:mappingnames_too_long				Mappingfeldnamen (#1) zu lang (max 10 Ziffern)
:cut_name					Ändere in: #1
:dbf_file_does_not_exist			DBF-Datei (#1) existiert nicht!
:hint_read_header_csv				Lese Datei Header CSV
:hint_read_header_mdb				Lese Datei Header ACCESS
:access_tabellen				Access Tabellen
:read_header_mdb				Lese Dateiheader
