#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:        ghc_mapping_definator.msg
##
## Description: Message file for message handler ghc_mapping_definator
##
## Author:      Jan Kiefer
## Date:        31. Mar 2006
##
## Copyright (C) GIT HydroS Consult GmbH. All Rights Reserved.
##
##----------------------------------------------------------------------

:ds_selector?			Der GIT Mapping Definator dient zur Definition der Export-/Importfeldzuordnungen (Mappings) des GIT Communication Centers. Dieser Assistent soll Ihnen bei der Definition der Zuordnungen behilflich sein. Bitte wählen Sie den GIS Datenbestand der zu exportierenden oder importierenden Objektklasse.

:navigation				Navigation
:goto_view_selection			Datenbestandsauswahl
:goto_class_selection			Objektklassenauswahl
:goto_field_selection			Feldauswahl
:mapped_geofields			Zugeordnete Geometriefelder: #1
:geometry			  Geometrie
:data				 	Daten
:child_class_name_label			Kind-Objektklasse:
:myowner_class_name_list			Eltern-Objektklassen
:child_level				Kind-Ebene
:myowner_level				Eltern-Ebene
:none					Keine Zuordnungen definiert.
:mapping_definator_welcome		Willkommen
:actual_transfername			Transfername:
:gis_views				GIS VIEWS
:object_classes				Objektklassen
:class_name				Objektklasse
:fields					Felder
:external_fields			zu mappende externe Felder
:map_to					Map to
:zugeordnete_mappings			Feldzuordnungen:
:please_wait				Bitte warten...
:git_mapdef_sortiere			Tabellen der gewählten Datenbank werden analysiert
:level					Ebene
:internal_name				Interner Name:
:cancel					Abbruch
