#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          ghc_wizard_base.msg
##
## Description:   Message file for message handler ghc_wizard_base
##
## Author:        GIT HydroS Consult GmbH
## Date:          11. Jan 2011
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:title		Neuer Transfer anlegen
:enter_transfer_name  Bitte einen Transfernamen eintragen
:transfer_with_name_already_exists 	Es existiert bereits ein Transfer mit Namen '#1'.
