#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          ghc_wizard_base.msg
##
## Description:   Message file for message handler ghc_wizard_base
##
## Author:        GIT HydroS Consult GmbH
## Date:          11. Jan 2011
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:back		< Zurück
:next		Weiter >
:finish		Beenden
:cancel		Abbrechen
:reset		Zurücksetzen
:help		Hilfe
