#% text_encoding = iso8859_1

#------------------------------------------------------------------------------
#
#   I T S   I N F O R M A T I O N S T E C H N I K   S E R V I C E   G M B H
#  
#                          Fachschale Forstkataster
#
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
##
## Beschreibung	  : Meldungsdatei für it_forstkataster
##
## Autor	  : Jens Lüttke
##
## Datum	  : Dez. 2004
##		    
## Version        : 1.0 
##
#------------------------------------------------------------------------------

:it_fk_field_length_no_validation		:de_de
Die angegebene #1 entspricht nicht den Vorgaben: Numerisch, #2-stellig!



