#% text_encoding = iso8859_1
:follow_filter_ghc_cf_follow_ewa_la	Ohne Einschränkung
:follow_filter_ghc_cf_follow_ewa_la_material	Gleiches Material
:follow_filter_ghc_cf_follow_ewa_la_width_same	Gleiche Nennweite
:follow_filter_ghc_cf_follow_ewa_la_width_bigger	Größere Nennweite
:follow_filter_ghc_cf_follow_ewa_la_width_smaller	Kleinere Nennweite
:connection_la						Zuordnung Leitungsabschnitt
:connection_ha_la					Zuordnung HA-Leitungsabschnitt
:width_bigger						Profilbreite (kleiner werdend)
:width_smaller						Profilbreite (größer werdend)
:ghc_cf!width						Profilbreite
:ghc_cf!material					Material
:connection_strasse					Zuordnung Straße