:activate_style_def_dialog_for_raster_tt	Raster Farbverlauf
:activate_style_def_dialog_for_raster		Raster Farbverlauf
:activate_style_def_dialog_for_lines_tt		Isolinien Farbverlauf
:activate_style_def_dialog_for_lines		Isolinien Farbverlauf
:ghc_vt_altitude_dialog_for_raster_tt		Grenzwerte für Einfärbung (Raster)
:ghc_vt_altitude_dialog_for_raster		Grenzwerte für Einfärbung (Raster)
:create_iso_labels_tt				Erzeuge Beschriftungen
:create_iso_labels				Erzeuge Beschriftungen