#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          ghc_ggs_parent_message.msg
##
## Description:   Message file for message handler ghc_ggs_parent_message
##
## Author:        Uli Nädelin
## Date:          18. Mar 2010
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:no_change_in_value_for_ghc_distance_to_mean_gw	:de_de	Abs. mittlerer GW -> Keine Änderung
:no_change_in_value_for_ghc_distance_to_max_gw	:de_de	Abs. max. GW -> Keine Änderung
:no_change_in_value_for_ghc_distance_to_min_gw	:de_de	Abs. min. GW -> Keine Änderung

:changed_value_for_ghc_distance_to_mean_gw	:de_de	Abs. mittlerer GW -> Mit Änderung
:changed_value_for_ghc_distance_to_max_gw	:de_de	Abs. max. GW -> Mit Änderung
:changed_value_for_ghc_distance_to_min_gw	:de_de	Abs. min. GW -> Mit Änderung

:new_value_for_ghc_distance_to_mean_gw	:de_de	Abs. mittlerer GW -> Neuer Wert
:new_value_for_ghc_distance_to_max_gw	:de_de	Abs. max. GW -> Neuer Wert
:new_value_for_ghc_distance_to_min_gw	:de_de	Abs. min. GW -> Neuer Wert

:changed_value_increase_detail		:de_de	Der Abstand hat sich von zuvor #2 m auf #1 m vergrößert. Der Zuwachs beträgt #3 m.
:changed_value_decrease_detail		:de_de	Der Abstand hat sich von zuvor #2 m auf #1 m verringert. Die Kürzung beträgt #3 m.

:time_in_groundwater_added	:de_de	Zeitanteil GW-Beinfl. hinzugefügt
:time_in_groundwater_changed	:de_de	Zeitanteil GW-Beinfl. geändert
:time_in_groundwater_changed_detail	:de_de	Der Zeitanteil GW-Beinflussung hat sich von zuvor #2 % auf #1 % geändert.
:groundwater_state_added	:de_de	Grundwasserlage hinzugefügt
:groundwater_state_changed	:de_de	Grundwasserlage geändert
:groundwater_state_changed_detail	:de_de	Die Grundwasserlage hat sich von '#2' auf '#1' geändert.
:no_groundwater_value_in_area		Keine Grundwasserdaten vorhanden