:ghc_calculate_gw_impact_haltung			:de_de	Ermittelt die Lage im Grundwasser für alle AW Haltungen	
:ghc_calculate_gw_impact_schacht			:de_de	Ermittelt die Lage im Grundwasser für alle AW Schächte
:ghc_calculate_gw_impact_sonderbauwerk			:de_de	Ermittelt die Lage im Grundwasser für alls AW Sonderbauwerke
:ghc_calculate_gw_impact_revisionsschacht		:de_de	Ermittelt die Lage im Grundwasser für alle AW Revisionsschächte
:ghc_calculate_gw_impact_anschlussleitung		:de_de	Ermittelt die Lage im Grundwasser für alle AW Anschlussleitungen
:ghc_calculate_time_in_gw_error				:de_de	Die Zeit im Grundwasser konnte nicht bestimmt werden!
