:aw_haltung						:de_de	AW Haltung
:aw_sonderbauwerk					:de_de	AW Sonderbauwerk
:aw_revisionsschacht					:de_de	AW Revisionsschacht
:aw_schacht						:de_de	AW Schacht
:aw_anschluss_leitung					:de_de	AW Anschlussleitung
:aw_kanaluntersuchung					:de_de	AW Kanaluntersuchung
:aw_untersuchung					:de_de	AW Schachtuntersuchung
:ghc_calculate_groundwater_impact			:de_de	Berechne Lage im Grundwasser
:ghc_calculate_groundwater_impact_description		:de_de	Füllt das Feld "Lage im Grundwasser"
:ghc_calculate_groundwater_impact_short			:de_de	Ermittle Lage im Grundwasser
:no_height_information_found				:de_de	Es wurden keine Höheninformationen für dieses Objekt gefunden!	
:height_sohlende_used					:de_de	Verwendete Höhe: Rohrsohle Ende 
:height_sohlanfang_used					:de_de	Verwendete Höhe: Rohrsohle Anfang
:configuration_fault					:de_de	Konfigurationsfehler. Bitte überprüfen Sie die Einstellungen in der config.xml Datei der Applikation
:no_leitung_geometry_found				:de_de	Das Objekt hat keine Leitungs-Geometrie
:no_ggs_sgs_geometry_found				:de_de	Das Objekt hat keine für die Berechnung verwendbare Geometrie!
:no_schacht_geometry_found				:de_de	Das Objekt hat keine Mittelpunkts-Geometrie!
:missing_field_grundwasserlage				:de_de	Das Objekt hat kein Feld "Lage im Grundwasser"
:ghc_sohlhoehe_used					:de_de	Verwendete Höhe: Sohlhöhe
:ds_view_readonly					:de_de	Datenbank #1 hat kein Schreibrecht!
:m_waste_water_data_model				:de_de	Kanal