#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          ghc_copy_styles.msg
##
## Description:   Message file for message handler ghc_copy_styles
##
## Author:        Uli N‰delin
## Date:          07. Nov 2007
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:scale_does_not_exist		Im Ace '#2' existiert kein Style-Maﬂstab '#1'
:style_already_exist		Folgender Style existiert bereits (Klasse: #1, Feld: #5, SubStyleCode: #3, GeomCode: #4 und Style-Typ #2)
:style_created			Style angelegt (Klasse: #1, Feld: #5, SubStyleCode: #3, GeomCode: #4 und Style-Typ #2)
:collection_styles_copied		Styles der Klasse #1 wurden kopiert.
