#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          ghc_data_transfer_dm_functionality.msg
##
## Description:   Message file for message handler ghc_data_transfer_dm_functionality
##
## Author:        Uli Nädelin
## Date:          27. Feb 2009
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:start_datatransfer		:de_de	Veröffentliche Tabellen des Datentransfers