#% text_encoding = iso8859_1
##----------------------------------------------------------------------
##
## Name:          bplan_data_model.msg
##
## Description:   Message file for message handler bplan_data_model
##
## Author:        Jan Kiefer
## Date:          05. Aug 2008
##
##
## Copyright (C)  GIT HydroS Consult GmbH. 
##                Freiburg, Germany.
##                http://www.hydrosconsult.de  
##                All Rights Reserved.
##
##----------------------------------------------------------------------
:not_relevant_in_level		:de_de	Nicht relevant für aktuelle Ebene
:no_world_fnp_neu		:de_de	Andere Welt als 'FNP-Neu'
:skipped_world_fnp_neu		:de_de	Übersprungen, da Welt 'FNP-Neu'
:overlapment_exist		:de_de	Übersprungen, da Überschneidung mit FNP-Neu-Fläche
:no_area_geom			:de_de	Keine Flächengeometrie